// High-contrast starter config. Colours come from the High Contrast palette
// (palette/high-contrast.json), written between the palette markers by scripts/build-themes.py.
// Hyper cannot follow the system light and dark setting, so it carries the dark half.

module.exports = {
  config: {
    fontSize: 13,
    fontFamily: '"Consolas", monospace',
    // palette start, generated by scripts/build-themes.py from palette/high-contrast.json
    backgroundColor: "#000000",
    foregroundColor: "#e0e0e0",
    cursorColor: "#ffffff",
    selectionColor: "#273d4c",
    colors: {
      black: "#35424c",
      red: "#ff0f00",
      green: "#00ff2f",
      yellow: "#fff500",
      blue: "#8ac9ff",
      magenta: "#ff66ff",
      cyan: "#6ff7ff",
      white: "#f2f2f2",
      lightBlack: "#465c6d",
      lightRed: "#df6c5a",
      lightGreen: "#79be7e",
      lightYellow: "#ffdb20",
      lightBlue: "#67b5ed",
      lightMagenta: "#ff99ff",
      lightCyan: "#84dde0",
      lightWhite: "#ffffff",
    },
    // palette end
    scrollback: 10000,
  },
  plugins: [],
  keymaps: {},
};
