#!/usr/bin/env python3
"""Writes every terminal's theme files from palette/high-contrast.json.

The palette is the single source of truth. The dark half is vivid, saturated colours on black; the
light half takes the same hues, kept as saturated as possible and darkened until each reaches at
least 7:1 (WCAG AAA) on white. Every file this script writes is
generated, so edit the palette and run the script again rather than editing an output by hand. `--check` exits non-zero when a committed file is out of date, which CI runs.
"""

import json
import plistlib
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTE = json.loads((ROOT / "palette" / "high-contrast.json").read_text())
NAMES = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
PLATFORMS = ["mac", "linux", "windows"]
HEADER = "generated by scripts/build-themes.py from palette/high-contrast.json, do not edit by hand"

# a fixed Guid, so regenerating never creates a second iTerm2 profile beside the first
ITERM_GUID = str(uuid.uuid5(uuid.NAMESPACE_URL, "terminal-config/high-contrast"))


def rgb(hex_colour):
    return [int(hex_colour[i:i + 2], 16) / 255 for i in (1, 3, 5)]


def mode_title(mode):
    return f"{PALETTE['name']} {mode.capitalize()}"


def colours16(mode):
    return PALETTE[mode]["ansi"] + PALETTE[mode]["bright"]


def alacritty(mode):
    m = PALETTE[mode]
    lines = [f"# {HEADER}", "", "[colors.primary]", f'background = "{m["background"]}"',
             f'foreground = "{m["foreground"]}"', "", "[colors.cursor]", f'cursor = "{m["cursor"]}"',
             f'text = "{m["background"]}"', "", "[colors.selection]",
             f'background = "{m["selection_background"]}"', f'text = "{m["selection_foreground"]}"']
    for kind in ("normal", "bright"):
        lines += ["", f"[colors.{kind}]"]
        values = m["ansi"] if kind == "normal" else m["bright"]
        lines += [f'{name} = "{value}"' for name, value in zip(NAMES, values)]
    return "\n".join(lines) + "\n"


def kitty(mode):
    m = PALETTE[mode]
    lines = [f"# {HEADER}", f"background {m['background']}", f"foreground {m['foreground']}",
             f"cursor {m['cursor']}", f"cursor_text_color {m['background']}",
             f"selection_background {m['selection_background']}",
             f"selection_foreground {m['selection_foreground']}"]
    lines += [f"color{i} {value}" for i, value in enumerate(colours16(mode))]
    return "\n".join(lines) + "\n"


def warp(mode):
    m = PALETTE[mode]
    lines = [f"# {HEADER}", f"name: {mode_title(mode)}", f"accent: '{m['ansi'][4]}'",
             f"background: '{m['background']}'", f"foreground: '{m['foreground']}'",
             f"details: {'darker' if mode == 'dark' else 'lighter'}", "terminal_colors:"]
    for kind, values in (("normal", m["ansi"]), ("bright", m["bright"])):
        lines.append(f"  {kind}:")
        lines += [f"    {name}: '{value}'" for name, value in zip(NAMES, values)]
    return "\n".join(lines) + "\n"


HYPER_START = "    // palette start, generated by scripts/build-themes.py from palette/high-contrast.json\n"
HYPER_END = "    // palette end\n"


def hyper(current):
    # Hyper cannot follow the system light and dark setting, so it carries the dark half only. Only
    # the block between the palette markers is rewritten, so each platform keeps its own font
    m = PALETTE["dark"]
    colours = "".join(
        [f'      {name}: "{value}",\n' for name, value in zip(NAMES, m["ansi"])]
        + [f'      light{name.capitalize()}: "{value}",\n' for name, value in zip(NAMES, m["bright"])])
    block = (HYPER_START
             + f'    backgroundColor: "{m["background"]}",\n'
             + f'    foregroundColor: "{m["foreground"]}",\n'
             + f'    cursorColor: "{m["cursor"]}",\n'
             + f'    selectionColor: "{m["selection_background"]}",\n'
             + "    colors: {\n" + colours + "    },\n"
             + HYPER_END)
    if HYPER_START not in current or HYPER_END not in current:
        raise SystemExit("hyper.js is missing the palette start and end markers")
    before = current[:current.index(HYPER_START)]
    after = current[current.index(HYPER_END) + len(HYPER_END):]
    return before + block + after


def iterm_colour(hex_colour):
    r, g, b = rgb(hex_colour)
    return {"Red Component": r, "Green Component": g, "Blue Component": b,
            "Alpha Component": 1, "Color Space": "sRGB"}


def iterm():
    profile = {
        "Name": PALETTE["name"],
        "Guid": ITERM_GUID,
        # everything else (font, bell, scrollback) is inherited from the profile named Default
        "Dynamic Profile Parent Name": "Default",
        "Use Separate Colors for Light and Dark Mode": True,
        "Use Bright Bold": False,
    }
    for mode, suffix in (("dark", " (Dark)"), ("light", " (Light)")):
        m = PALETTE[mode]
        for key, value in (("Background Color", m["background"]), ("Foreground Color", m["foreground"]),
                           ("Bold Color", m.get("bold", m["foreground"])), ("Cursor Color", m["cursor"]),
                           ("Cursor Text Color", m["background"]),
                           ("Selection Color", m["selection_background"]),
                           ("Selected Text Color", m["selection_foreground"])):
            profile[key + suffix] = iterm_colour(value)
        for i, value in enumerate(colours16(mode)):
            profile[f"Ansi {i} Color{suffix}"] = iterm_colour(value)
    return json.dumps({"Profiles": [profile]}, indent=2) + "\n"


def ns_archive(root_object, class_name, extra_classes):
    return plistlib.dumps({
        "$archiver": "NSKeyedArchiver",
        "$version": 100000,
        "$top": {"root": plistlib.UID(1)},
        "$objects": ["$null", root_object] + extra_classes
        + [{"$classname": class_name, "$classes": [class_name, "NSObject"]}],
    }, fmt=plistlib.FMT_BINARY)


def ns_colour(hex_colour):
    # NSSpaceID 12 is sRGB, so Terminal.app shows exactly the palette's values. The device RGB form
    # its older built-in profiles use is converted to the display's own space and comes out darker
    components = (" ".join(f"{c:.10g}" for c in rgb(hex_colour)) + " 1").encode()
    return plistlib.dumps({
        "$archiver": "NSKeyedArchiver",
        "$version": 100000,
        "$top": {"root": plistlib.UID(1)},
        "$objects": [
            "$null",
            {"NSColorSpace": 1, "NSComponents": components, "NSRGB": components + b"\x00",
             "NSCustomColorSpace": plistlib.UID(2), "$class": plistlib.UID(4)},
            {"NSSpaceID": 12, "$class": plistlib.UID(3)},
            {"$classname": "NSColorSpace", "$classes": ["NSColorSpace", "NSObject"]},
            {"$classname": "NSColor", "$classes": ["NSColor", "NSObject"]},
        ],
    }, fmt=plistlib.FMT_BINARY)


def ns_font(name, size):
    obj = {"NSName": plistlib.UID(2), "NSSize": float(size), "NSfFlags": 16, "$class": plistlib.UID(3)}
    return ns_archive(obj, "NSFont", [name])


TERMINAL_APP_KEYS = ["ANSIBlackColor", "ANSIRedColor", "ANSIGreenColor", "ANSIYellowColor",
                     "ANSIBlueColor", "ANSIMagentaColor", "ANSICyanColor", "ANSIWhiteColor",
                     "ANSIBrightBlackColor", "ANSIBrightRedColor", "ANSIBrightGreenColor",
                     "ANSIBrightYellowColor", "ANSIBrightBlueColor", "ANSIBrightMagentaColor",
                     "ANSIBrightCyanColor", "ANSIBrightWhiteColor"]


def terminal_app(mode):
    m = PALETTE[mode]
    profile = {
        "name": mode_title(mode),
        "type": "Window Settings",
        "ProfileCurrentVersion": 2.09,
        "BackgroundColor": ns_colour(m["background"]),
        "TextColor": ns_colour(m["foreground"]),
        "TextBoldColor": ns_colour(m.get("bold", m["foreground"])),
        "CursorColor": ns_colour(m["cursor"]),
        "SelectionColor": ns_colour(m["selection_background"]),
        "Font": ns_font("SFMonoTerminal-Regular", 12),
        "FontAntialias": True,
        # bold keeps the normal colour rather than switching to the softer bright row
        "UseBrightBold": False,
        "columnCount": 120,
        "rowCount": 32,
    }
    for key, value in zip(TERMINAL_APP_KEYS, colours16(mode)):
        profile[key] = ns_colour(value)
    return plistlib.dumps(profile, fmt=plistlib.FMT_XML, sort_keys=True)


def windows_terminal():
    keys = ["black", "red", "green", "yellow", "blue", "purple", "cyan", "white"]
    schemes = []
    for mode in ("dark", "light"):
        m = PALETTE[mode]
        scheme = {"name": mode_title(mode), "background": m["background"], "foreground": m["foreground"],
                  "cursorColor": m["cursor"], "selectionBackground": m["selection_background"]}
        scheme.update(dict(zip(keys, m["ansi"])))
        scheme.update({"bright" + k.capitalize(): v for k, v in zip(keys, m["bright"])})
        schemes.append(scheme)
    return json.dumps({"$help": HEADER, "schemes": schemes}, indent=2) + "\n"


def ptyxis():
    lines = [f"# {HEADER}", "[Palette]", f"Name={PALETTE['name']}"]
    for mode in ("light", "dark"):
        m = PALETTE[mode]
        lines += ["", f"[{mode.capitalize()}]", f"Foreground={m['foreground']}",
                  f"Background={m['background']}", f"Cursor={m['cursor']}"]
        lines += [f"Color{i}={value}" for i, value in enumerate(colours16(mode))]
    return "\n".join(lines) + "\n"


def gnome_terminal():
    # GNOME Terminal (Ubuntu 24.04) has no light and dark palette pair, so it takes the dark half
    m = PALETTE["dark"]
    palette = ", ".join(f"'{c}'" for c in colours16("dark"))
    return f"""# {HEADER}
# load with: dconf load /org/gnome/terminal/legacy/profiles:/:<profile id>/ < high-contrast-dark.dconf
[/]
use-theme-colors=false
background-color='{m['background']}'
foreground-color='{m['foreground']}'
bold-is-bright=false
cursor-colors-set=true
cursor-background-color='{m['cursor']}'
cursor-foreground-color='{m['background']}'
highlight-colors-set=true
highlight-background-color='{m['selection_background']}'
highlight-foreground-color='{m['selection_foreground']}'
palette=[{palette}]
"""


TABLE_START = "<!-- palette table start: generated by scripts/build-themes.py -->\n"
TABLE_END = "<!-- palette table end -->\n"
SLOT_NAMES = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]


def palette_table(current):
    # the guide's colour table is generated too, so the documented values can never drift
    def cell(mode, value):
        return f"`{value}` ({contrast(value, PALETTE[mode]['background']):.1f}:1)"
    rows = ["| Colour | Dark mode | Light mode |", "| --- | --- | --- |"]
    for key, label in (("foreground", "Text"), ("background", "Background")):
        rows.append(f"| {label} | `{PALETTE['dark'][key]}` | `{PALETTE['light'][key]}` |")
    for kind, prefix in (("ansi", ""), ("bright", "Bright ")):
        for name, dark, light in zip(SLOT_NAMES, PALETTE["dark"][kind], PALETTE["light"][kind]):
            rows.append(f"| {prefix}{name} | {cell('dark', dark)} | {cell('light', light)} |")
    block = TABLE_START + "\n".join(rows) + "\n" + TABLE_END
    if TABLE_START not in current or TABLE_END not in current:
        raise SystemExit("the guide is missing the palette table markers")
    return current[:current.index(TABLE_START)] + block + current[current.index(TABLE_END) + len(TABLE_END):]


def outputs():
    # a terminal's files are written only where the repo already has that terminal's folder, so the
    # same script serves a repo that covers fewer terminals
    files = {}
    for platform in PLATFORMS:
        base = ROOT / platform
        for mode in ("dark", "light"):
            if (base / "alacritty").is_dir():
                files[f"{platform}/alacritty/high-contrast-{mode}.toml"] = alacritty(mode)
            if (base / "kitty").is_dir():
                files[f"{platform}/kitty/{mode}-theme.auto.conf"] = kitty(mode)
            if (base / "warp").is_dir():
                files[f"{platform}/warp/themes/high-contrast-{mode}.yaml"] = warp(mode)
        if (base / "kitty").is_dir():
            # kitty uses this one when the system reports no preference
            files[f"{platform}/kitty/no-preference-theme.auto.conf"] = kitty("dark")
        hyper_file = base / "hyper" / "hyper.js"
        if hyper_file.exists():
            files[f"{platform}/hyper/hyper.js"] = hyper(hyper_file.read_text())
    files["mac/iterm2/high-contrast.json"] = iterm()
    for mode in ("dark", "light"):
        files[f"mac/terminal-app/{mode_title(mode)}.terminal"] = terminal_app(mode)
    files["windows/windows-terminal/high-contrast.json"] = windows_terminal()
    files["linux/ptyxis/high-contrast.palette"] = ptyxis()
    files["linux/gnome-terminal/high-contrast-dark.dconf"] = gnome_terminal()
    guide = ROOT / "guides" / "high-contrast.md"
    if guide.exists():
        files["guides/high-contrast.md"] = palette_table(guide.read_text())
    return files


def luminance(hex_colour):
    channels = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in rgb(hex_colour)]
    return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2]


def contrast(a, b):
    high, low = sorted((luminance(a), luminance(b)), reverse=True)
    return (high + 0.05) / (low + 0.05)


def low_contrast():
    # light mode holds every text colour to 7:1 (WCAG AAA) on white. Dark mode favours saturation,
    # which keeps colours easy to tell apart, with a floor of 4.5:1 (WCAG AA); its two blacks are
    # exempt, since they are background shades and dim hint text by design
    problems = []
    for mode, floor, exempt in (("dark", 4.5, {0, 8}), ("light", 7, set())):
        m = PALETTE[mode]
        checks = [("foreground", m["foreground"], m["background"]),
                  ("selection", m["selection_foreground"], m["selection_background"])]
        checks += [(f"color{i}", value, m["background"])
                   for i, value in enumerate(colours16(mode)) if i not in exempt]
        problems += [f"{mode} {name} {ratio:.1f}:1" for name, fg, bg in checks
                     if (ratio := contrast(fg, bg)) < floor]
    return problems


def main():
    check = "--check" in sys.argv[1:]
    problems = low_contrast()
    if problems:
        print("below the contrast floor:\n  " + "\n  ".join(problems))
        sys.exit(1)
    stale = []
    for relative, content in outputs().items():
        path = ROOT / relative
        data = content if isinstance(content, bytes) else content.encode()
        if path.exists() and path.read_bytes() == data:
            continue
        if check:
            stale.append(relative)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {relative}")
    if stale:
        print("out of date, run scripts/build-themes.py:\n  " + "\n  ".join(stale))
        sys.exit(1)


if __name__ == "__main__":
    main()
